# Generated by Django 3.2.8 on 2021-10-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0002_alter_productcategory_options'),
        ('eshop_products', '0003_auto_20211025_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='eshop_products_category.ProductCategory', verbose_name=' دسته بندی ها'),
        ),
    ]
